version: '3'

services:

  api:
    build:
      context: .
      dockerfile: ./server/Dockerfile
    container_name: joblog-api
    environment:
        APP_ENV: dev
        DATABASE_URL: 'mysql://root:example@database:3306/joblog?serverVersion8.0'
        CORS_ALLOW_ORIGIN: '^https?://(localhost|127\.0\.0\.1)(:[0-9]+)?$'
    ports:
      - "8000:80"
    depends_on:
      - database
      
  database:
      image: mysql:8
      container_name: joblog-database
      ports:
        - "33067:3306"
      volumes:
        - ./data:/var/lib/mysql
      command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
      restart: always
      environment:
        MYSQL_ROOT_PASSWORD: example
