job_index:
    path: /api/v1/jobs
    controller: App\Controller\JobController::indexAction
    methods: [GET]

job_create:
    path: /api/v1/jobs
    controller: App\Controller\JobController::createAction
    methods: [POST]

property_index:
    path: /api/v1/properties
    controller: App\Controller\PropertyController::indexAction
    methods: [GET]

property_create:
    path: /api/v1/properties
    controller: App\Controller\PropertyController::createAction
    methods: [POST]

user_index:
    path: /api/v1/users
    controller: App\Controller\UserController::indexAction
    methods: [GET]
